### ISSUE TITLE
.Net: Bug - Expected 'MappingStart', got 'SequenceStart' with FunctionCallingStepwisePlanner

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/semantic-kernel#4338]
**Describe the bug**
When invoking a stepwise planner, I'm always facing the same issue.

**To Reproduce**
1. Instanciate a stepwise planner: 
```csharp
var config = new FunctionCallingStepwisePlannerConfig
{
    MaxIterations = 15,
    MaxTokens = 4000,
};
var planner = new FunctionCallingStepwisePlanner(config);

var result = await planner.ExecuteAsync(this._kernel, goal).ConfigureAwait(false)
```

**Expected behavior**
FunctionCallingStepwisePlanner should be invoking correctly.

**Screenshots**

```txt
YamlDotNet.Core.YamlException : Expected 'MappingStart', got 'SequenceStart' (at Line: 26, Col: 3, Idx: 1203).

  Stack Trace: 
ParserExtensions.Require[T](IParser parser)
ParserExtensions.Consume[T](IParser parser)
DictionaryDeserializer.Deserialize(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
DictionaryNodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
<>c__DisplayClass4_0.<DeserializeValue>b__0(IParser r, Type t)
ObjectNodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
<5 more frames...>
PromptYamlKernelExtensions.CreateFunctionFromPromptYaml(Kernel kernel, String text, IPromptTemplateFactory promptTemplateFactory)
FunctionCallingStepwisePlanner.GeneratePlanAsync(String question, Kernel kernel, ILogger logger, CancellationToken cancellationToken)
FunctionCallingStepwisePlanner.ExecuteCoreAsync(Kernel kernel, String question, CancellationToken cancellationToken)
PlannerInstrumentation.InvokePlanAsync[TPlan,TPlanInput,TPlanResult](Func`5 InvokePlanAsync, TPlan plan, Kernel kernel, TPlanInput input, ILogger logger, CancellationToken cancellationToken)
```

**Platform**
 - OS: N/A
 - IDE: N/A
 - Language: C#
 - Source: RC4

**Additional context**

**Comment by josephsctan** [comment]
I am experiencing the same issue.
Interestingly, the example from the semantic kernel start project works. [Example66_FunctionCallingStepwisePlanner](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example66_FunctionCallingStepwisePlanner.cs )
Stepping through the example will probably identify the problem (when I find some time)

**Comment by kbeaugrand** [comment]
@markwallace-microsoft, it seems that it duplicates the #4296 that is already fixed?

**Comment by markwallace-microsoft** [comment]
Thanks @kbeaugrand yes, it's the same issue

**Comment by rosieks** [comment]
@markwallace-microsoft Could you add in witch version it's fixed. I still get this error. Today I just updated all nugets
